Bump version to 2023.05.31 with many improvements: - If there is a voidnsrun glibc container it changes the mirrors for it too. - Correct unnecessary echo at cereus-results. - Clarify about tier 2 and tier 3 mirrors. - Don't remove previous repositories configs, instead, overwrite them. - Don't copy fallback debug repository to /etc/xbps.d, just remove it to leave defaults.

diff --git a/xrankmirrors b/xrankmirrors
--- a/xrankmirrors
+++ b/xrankmirrors
@@ -7,8 +7,9 @@ cachedir="/var/cache/xrankmirrors"
 void_file="$cachedir/void-results"
 cereus_file="$cachedir/cereus-results"
 cereus_pkg="cereus-extra/$arch/$(xbps-query -R -S xidlehook | grep pkgver | cut -d' ' -f2).$arch.xbps"
-VERSION="2023.02.13"
+VERSION="2023.05.31"
 region_sel=""
+voidnsrun_container=""
 CLI_BOLD=$(tput bold)
 CLI_RESET=$(tput sgr0)
 dialog_conf="/tmp/xrankmirrors-dialogrc"
@@ -192,8 +193,6 @@ run_ranks() {
     format
 }
 
-echo "${mirror_cereus},${region},${loc},${tier},${provider},${dlspeed},${connect}" >> "$cereus_file"
-
 get_fastests() {
         echo ""
         echo "${CLI_BOLD}Fastest mirrors:${CLI_RESET}"
@@ -220,6 +219,7 @@ set_fastests() {
     fi
 
     get_fastests
+    change_container_mirror
     change_mirror
 }
 
@@ -273,9 +273,9 @@ EOF
 
     CEREUSMSG=$(fold -sw 76 <<EOF
 
-Tier ${RED}1${RESET} mirrors have all the packages available in both ${RED}cereus-extra${RESET} and ${RED}cereus-core${RESET} repositories and will always have the latest packages available. 
+${RED}Tier 1${RESET} mirrors have all the packages available in both ${RED}cereus-extra${RESET} and ${RED}cereus-core${RESET} repositories and will always have the latest packages available. 
 
-Tier ${RED}2${RESET} mirrors are limited by 100MB limit size on packages, this make heavy packages like ${RED}OnlyOffice${RESET}, ${RED}Brave${RESET} or ${RED}Heroic${RESET} unavailable in them. You can choose them ${BOLD}only if you are ok with that${RESET}.
+${RED}Tier 2${RESET} mirrors are limited at ~150MB size on packages, and ${RED}Tier 3${RESET} mirrors are limited at 100MB. This make some heavy packages unavailable in them (${RED}OnlyOffice${RESET} for tier 2, ${RED}Brave${RESET} and ${RED}Heroic${RESET} for tier 3). You can choose them ${BOLD}only if you are ok with that${RESET}.
 EOF
 )
     DIALOG() {
@@ -290,21 +290,27 @@ EOF
     if [ $run_yesno = "Yes" ]; then
         region_prompt
         run_ranks
-    fi
-    
-    if [ ! -e $cereus_file ] || [ ! -e $void_file ]; then
-        echo -e "\e[1;31mError: No cache file found! Please run the mirrors test first."
-        read -n 1 -s -r -p "Press any key to exit..."
-        exit 1
+        select_mirror
+    else
+        if [ ! -e $cereus_file ] || [ ! -e $void_file ]; then
+            echo -e "\e[1;31mError: No cache file found! Please run the mirrors test first."
+            read -n 1 -s -r -p "Press any key to exit..."
+            exit 1
+        else
+            select_mirror
+        fi
     fi
 
+    change_container_mirror
+    change_mirror
+}
+
+select_mirror() {
     DIALOG --title "${BOLD} Important note about Cereus Linux mirrors ${RESET}" --msgbox "$CEREUSMSG" 15 80
     cereus_mirror=$(cat $cereus_file | fzf --layout=reverse --header-lines=1 --border --border-label="Please select a mirror for Cereus repositories" | awk -F' ' '{ print $1 }')
 
     DIALOG --title "${BOLD} Important note about Void Linux mirrors ${RESET}" --msgbox "$VOIDMSG" 15 80
     void_mirror=$(cat $void_file | fzf --layout=reverse --header-lines=1 --border --border-label="Please select a mirror for Void repositories" | awk -F' ' '{ print $1 }')
-
-    change_mirror
 }
 
 change_mirror() {
@@ -313,13 +319,11 @@ change_mirror() {
     fi
 
     if [ -n "$cereus_mirror" ]; then
-        rm /etc/xbps.d/*cereus*.conf
         cp /usr/share/xbps.d/*cereus*.conf /etc/xbps.d/
         sed -i 's|https://sourceforge.net/projects/cereus-linux/files/repos/|'"$cereus_mirror"'|g' /etc/xbps.d/*cereus*.conf
     fi
 
     if [ -n "$void_mirror" ]; then
-        rm /etc/xbps.d/*repository*.conf
         cp /usr/share/xbps.d/*repository*.conf /etc/xbps.d/
         sed -i 's|https://repo-default.voidlinux.org/|'"$void_mirror"'|g' /etc/xbps.d/*repository*.conf     
     fi
@@ -329,13 +333,43 @@ change_mirror() {
         debug_repo=$(cat /etc/xbps.d/20-repository-debug.conf | cut -d"=" -f2)
         if ! (wget --spider "$debug_repo/$arch-repodata" 2>/dev/null); then
             echo "Selected mirror does not have debug repository, falling back to default"
-             cp /usr/share/xbps.d/20-repository-debug.conf /etc/xbps.d/
+            rm /etc/xbps.d/20-repository-debug.conf
         fi
     fi
 
     echo "${CLI_BOLD}=> Updating XBPS repositories database...${CLI_RESET}"
     xbps-install -S
     read -n 1 -s -r -p "${CLI_BOLD}=> Mirror changed. Press any key to exit...${CLI_RESET}"
+}
+
+change_container_mirror() {
+    # If there is a voidnsrun glibc container, also apply changes for it.
+    if [ -e /glibc/usr/share/xbps.d ]; then
+        echo "${CLI_BOLD}=> voidnsrun glibc container detected, changing mirrors for it too...${CLI_RESET}"
+        if [ ! -e /glibc/etc/xbps.d/ ]; then
+            mkdir -p /glibc/etc/xbps.d/
+        fi
+
+        if [ -n "$cereus_mirror" ]; then
+            cp /glibc/usr/share/xbps.d/*cereus*.conf /glibc/etc/xbps.d/
+            sed -i 's|https://sourceforge.net/projects/cereus-linux/files/repos/|'"$cereus_mirror"'|g' /glibc/etc/xbps.d/*cereus*.conf
+        fi
+
+        if [ -n "$void_mirror" ]; then
+            cp /glibc/usr/share/xbps.d/*repository*.conf /glibc/etc/xbps.d/
+            sed -i 's|https://repo-default.voidlinux.org/|'"$void_mirror"'|g' /glibc/etc/xbps.d/*repository*.conf     
+        fi
+
+        # Test if selected mirror has debug repository
+        if [ -e /glibc/usr/share/xbps.d/20-repository-debug.conf ]; then
+            debug_repo=$(cat /glibc/etc/xbps.d/20-repository-debug.conf | cut -d"=" -f2)
+            if ! (wget --spider "$debug_repo/$arch-repodata" 2>/dev/null); then
+                echo "Selected mirror does not have debug repository, falling back to default"
+                rm /glibc/etc/xbps.d/20-repository-debug.conf
+            fi
+    fi
+        xchroot /glibc xbps-install -S
+     fi
 }
 
 help() {
@@ -366,7 +400,7 @@ case $opt in
     g) run_ranks; print_results ;;
     h) help; exit 1;;
     i) xrankfzf ;;
-    m) change_mirror ;;
+    m) change_container_mirror; change_mirror ;;
     r) region_sel="$OPTARG";;
     s) set_fastests;;
     v) void_mirror="$OPTARG";;
